import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.menu': 'Menu',
    'nav.help': 'Help',
    'nav.book': 'Book Now',
    'nav.destinations': 'Destinations',
    'nav.discover': 'Discover',
    'nav.socials': 'Socials',
    'nav.portal': 'Operator Portal',
    'nav.scam_guide': 'Scam Prevention',
    'nav.compare': 'Compare',
    'nav.select_lang': 'Select Language',
    'hero.the_sahara': 'The Sahara',
    'hero.verified': 'Verified',
    'hero.handpicked': 'Handpicked',
    'hero.expert': "Morocco's Verified Desert Expert",
    'home.find_your_camp': 'Find your dream desert camp',
    'home.top_rated': 'Top Rated Experiences',
    'home.view_all': 'View All',
    'home.compare_desc': 'Each destination offers a unique rhythm. From high dunes to stone silence.',
    'home.compare_action': 'Compare Destinations',
    'footer.desc': 'The only specialized booking platform for verified luxury desert camps in Morocco. Experience Merzouga, Zagora, Agafay, and Foum Zguid with absolute peace of mind. No scams, just magic.',
    'footer.destinations': 'Destinations',
    'footer.trust': 'Trust',
    'footer.scam_guide': 'Scam Prevention Guide',
    'footer.compare': 'Compare Dunes',
    'footer.partners': 'Join as Operator',
    'footer.built_for': 'Built for modern explorers.',
    'search.destination': 'Destination',
    'search.arrival': 'Arrival',
    'search.guests': 'Guests',
    'search.action': 'Search',
    'search.merzouga': 'Merzouga Desert',
    'search.zagora': 'Zagora Desert',
    'search.agafay': 'Agafay (Marrakech)',
    'search.foumzguid': 'Foum Zguid Desert',
    'camp.night': '/ night',
    'camp.bath': 'Private Bath',
    'camp.guests': 'Up to {count} guests',
    'camp.availability': 'Availability: Today',
    'camp.details': 'View Details',
    'hub.explorer': 'Destination Explorer',
    'hub.filters': 'Filters',
    'hub.tier': 'Verification Tier',
    'hub.price': 'Price Range',
    'hub.trust_title': 'Trust Verified',
    'hub.trust_desc': 'Physically inspected camps. No hidden fees.',
    'hub.trust_action': 'Learn about verification',
    'hub.showing': 'Showing {count} camps',
    'hub.map': 'View on Map',
    'hub.none': 'No camps found.',
    'hub.planning': 'Planning Your Stay',
    'home.trust_hook': 'We physically verify every camp so you don\'t have to. No scams, no stress, just the magic of the dunes.',
    'home.scam_title': 'Planning a Moroccan desert trip? Don\'t get scammed.',
    'home.scam_desc': 'From "fake camps" to hidden transportation fees, the desert can be tricky. We\'ve built the world\'s first trust-first booking platform for Sahara explorers.',
    'home.scam_action': 'Read the Definitive Scam Guide',
    'detail.back': 'Back to Exploration',
    'detail.photos': 'View All Photos',
    'detail.reviews': '{count} Reviews',
    'detail.experience': 'The Experience',
    'detail.why_verified': 'Why this camp is {tier}',
    'detail.available': 'Available',
    'detail.dates': 'Dates',
    'detail.tent_type': 'Tent Type',
    'detail.service_fee': 'Service Fee',
    'detail.total': 'Total',
    'detail.reserve': 'Reserve Now',
    'detail.charge_notice': "You won't be charged yet. We'll verify availability in real-time.",
    'amenity.bath': 'Private Bathroom',
    'amenity.climate': 'AC / Heating',
    'amenity.food': 'Traditional Breakfast',
    'amenity.guests': 'Max {count} Guests',
    'amenity.wifi': 'Desert WiFi',
    'scam.guide_title': 'Don\'t Let a Scam Ruin Your Sahara Magic.',
    'scam.guide_subtitle': 'The desert is beautiful, but the booking ecosystem can be treacherous. We built this guide (and our platform) to ensure you only experience the magic.',
    'scam.the_scam': 'The Scam',
    'scam.prevention': 'Prevention',
    'scam.promise_title': 'The Dunecamps Promise',
    'scam.ready': 'Ready to book with peace of mind?',
    'scam.explore_action': 'Explore Elite Camps',
  },
  fr: {
    'nav.menu': 'Menu',
    'nav.help': 'Aide',
    'nav.book': 'Réserver',
    'nav.destinations': 'Destinations',
    'nav.discover': 'Découvrir',
    'nav.socials': 'Réseaux',
    'nav.portal': 'Portail Opérateur',
    'nav.scam_guide': 'Prévention Arnaques',
    'nav.compare': 'Comparer',
    'nav.select_lang': 'Choisir Langue',
    'hero.the_sahara': 'Le Sahara',
    'hero.verified': 'Vérifié',
    'hero.handpicked': 'Sélectionné',
    'hero.expert': "L'expert du désert vérifié au Maroc",
    'home.find_your_camp': 'Trouvez votre camp de désert idéal',
    'home.top_rated': 'Expériences les mieux notées',
    'home.view_all': 'Voir tout',
    'home.compare_desc': 'Chaque destination offre son propre rythme. Des hautes dunes au silence de pierre.',
    'home.compare_action': 'Comparer Destinations',
    'footer.desc': 'La seule plateforme de réservation spécialisée pour les camps de désert de luxe vérifiés au Maroc. Vivez Merzouga, Zagora, Agafay et Foum Zguid en toute sérénité. Pas d\'arnaques, que de la magie.',
    'footer.destinations': 'Destinations',
    'footer.trust': 'Confiance',
    'footer.scam_guide': 'Guide de prévention des arnaques',
    'footer.compare': 'Comparer les dunes',
    'footer.partners': 'Devenir partenaire',
    'footer.built_for': 'Conçu pour les explorateurs modernes.',
    'search.destination': 'Destination',
    'search.arrival': 'Arrivée',
    'search.guests': 'Voyageurs',
    'search.action': 'Rechercher',
    'search.merzouga': 'Désert de Merzouga',
    'search.zagora': 'Désert de Zagora',
    'search.agafay': 'Agafay (Marrakech)',
    'search.foumzguid': 'Désert de Foum Zguid',
    'camp.night': '/ nuit',
    'camp.bath': 'Bain Privé',
    'camp.guests': 'Jusqu\'à {count} invités',
    'camp.availability': 'Disponibilité: Aujourd\'hui',
    'camp.details': 'Voir Détails',
    'hub.explorer': 'Explorateur de Destinations',
    'hub.filters': 'Filtres',
    'hub.tier': 'Niveau de vérification',
    'hub.price': 'Gamme de prix',
    'hub.trust_title': 'Confiance Vérifiée',
    'hub.trust_desc': 'Camps inspectés physiquement. Pas de frais cachés.',
    'hub.trust_action': 'En savoir plus',
    'hub.showing': 'Affichage de {count} camps',
    'hub.map': 'Voir sur la carte',
    'hub.none': 'Aucun camp trouvé.',
    'hub.planning': 'Planifier votre séjour',
    'home.trust_hook': 'Nous vérifions physiquement chaque camp pour que vous n\'ayez pas à le faire. Pas d\'arnaques, pas de stress, juste la magie des dunes.',
    'home.scam_title': 'Vous prévoyez un voyage dans le désert marocain ? Ne vous faites pas arnaquer.',
    'home.scam_desc': 'Des "faux camps" aux frais de transport cachés, le désert peut être piégeux. Nous avons construit la première plateforme de réservation axée sur la confiance.',
    'home.scam_action': 'Lire le guide définitif sur les arnaques',
    'detail.back': 'Retour à l\'exploration',
    'detail.photos': 'Voir toutes les photos',
    'detail.reviews': '{count} Avis',
    'detail.experience': 'L\'Expérience',
    'detail.why_verified': 'Pourquoi ce camp est {tier}',
    'detail.available': 'Disponible',
    'detail.dates': 'Dates',
    'detail.tent_type': 'Type de tente',
    'detail.service_fee': 'Frais de service',
    'detail.total': 'Total',
    'detail.reserve': 'Réserver maintenant',
    'detail.charge_notice': "Vous ne serez pas encore débité. Nous vérifierons la disponibilité en temps réel.",
    'amenity.bath': 'Salle de bain privée',
    'amenity.climate': 'Climatisation / Chauffage',
    'amenity.food': 'Petit-déjeuner traditionnel',
    'amenity.guests': 'Max {count} Personnes',
    'amenity.wifi': 'WiFi du désert',
    'scam.guide_title': 'Ne laissez pas une arnaque gâcher votre magie du Sahara.',
    'scam.guide_subtitle': 'Le désert est beau, mais l\'écosystème de réservation peut être périlleux. Nous avons construit ce guide pour vous assurer de ne vivre que la magie.',
    'scam.the_scam': 'L\'Arnaque',
    'scam.prevention': 'Prévention',
    'scam.promise_title': 'La Promesse Dunecamps',
    'scam.ready': 'Prêt à réserver en toute sérénité ?',
    'scam.explore_action': 'Explorer les camps d\'élite',
  },
  es: {
    'nav.menu': 'Menú',
    'nav.help': 'Ayuda',
    'nav.book': 'Reservar',
    'nav.destinations': 'Destinos',
    'nav.discover': 'Descubrir',
    'nav.socials': 'Redes sociales',
    'nav.portal': 'Portal de operadores',
    'nav.scam_guide': 'Prevención estafas',
    'nav.compare': 'Comparar',
    'nav.select_lang': 'Seleccionar idioma',
    'hero.the_sahara': 'El Sahara',
    'hero.verified': 'Verificado',
    'hero.handpicked': 'Seleccionado',
    'hero.expert': 'El experto verificado del desierto en Marruecos',
    'home.find_your_camp': 'Encuentra tu campamento en el desierto ideal',
    'home.top_rated': 'Experiencias mejor valoradas',
    'home.view_all': 'Ver todo',
    'home.compare_desc': 'Cada destino ofrece un ritmo único. Desde dunas altas hasta el silencio de la piedra.',
    'home.compare_action': 'Comparar destinos',
    'footer.desc': 'La única plataforma de reserva especializada en campamentos de lujo verificados en Marruecos. Descubre Merzouga, Zagora, Agafay y Foum Zguid con total tranquilidad. Sin estafas, solo magia.',
    'footer.destinations': 'Destinos',
    'footer.trust': 'Confianza',
    'footer.scam_guide': 'Guía de prevención de estafas',
    'footer.compare': 'Comparar dunas',
    'footer.partners': 'Unirse como operador',
    'footer.built_for': 'Creado para exploradores modernos.',
    'search.destination': 'Destino',
    'search.arrival': 'Llegada',
    'search.guests': 'Huéspedes',
    'search.action': 'Buscar',
    'search.merzouga': 'Desierto de Merzouga',
    'search.zagora': 'Desierto de Zagora',
    'search.agafay': 'Agafay (Marrakech)',
    'search.foumzguid': 'Desierto de Foum Zguid',
    'camp.night': '/ noche',
    'camp.bath': 'Baño Privado',
    'camp.guests': 'Hasta {count} personas',
    'camp.availability': 'Disponibilidad: Hoy',
    'camp.details': 'Ver Detalles',
    'hub.explorer': 'Explorador de Destinos',
    'hub.filters': 'Filtros',
    'hub.tier': 'Nivel de verificación',
    'hub.price': 'Rango de precios',
    'hub.trust_title': 'Confianza Verificada',
    'hub.trust_desc': 'Campamentos inspeccionados físicamente. Sin cargos ocultos.',
    'hub.trust_action': 'Más información',
    'hub.showing': 'Mostrando {count} campamentos',
    'hub.map': 'Ver en el mapa',
    'hub.none': 'No se encontraron campamentos.',
    'hub.planning': 'Planificando su estancia',
    'home.trust_hook': 'Verificamos físicamente cada campamento para que usted no tenga que hacerlo. Sin estafas, sin estrés, solo la magia de las dunas.',
    'home.scam_title': '¿Planeas un viaje al desierto de Marruecos? No te dejes estafar.',
    'home.scam_desc': 'Desde "campamentos falsos" hasta tarifas de transporte ocultas, el desierto puede ser complicado. Hemos creado la primera plataforma de reserva basada en la confianza.',
    'home.scam_action': 'Leer la guía definitiva sobre estafas',
    'detail.back': 'Volver a la exploración',
    'detail.photos': 'Ver todas las fotos',
    'detail.reviews': '{count} Reseñas',
    'detail.experience': 'La Experiencia',
    'detail.why_verified': 'Por qué este campamento es {tier}',
    'detail.available': 'Disponible',
    'detail.dates': 'Fechas',
    'detail.tent_type': 'Tipo de tienda',
    'detail.service_fee': 'Tarifa de servicio',
    'detail.total': 'Total',
    'detail.reserve': 'Reservar ahora',
    'detail.charge_notice': "Aún no se le cobrará. Verificaremos la disponibilidad en tiempo real.",
    'amenity.bath': 'Baño privado',
    'amenity.climate': 'Aire acondicionado / Calefacción',
    'amenity.food': 'Desayuno tradicional',
    'amenity.guests': 'Máx {count} Personas',
    'amenity.wifi': 'WiFi del desierto',
    'scam.guide_title': 'No dejes que una estafa arruine tu magia del Sahara.',
    'scam.guide_subtitle': 'El desierto es hermoso, pero el ecosistema de reservas puede ser traicionero. Creamos esta guía para asegurar que solo vivas la magia.',
    'scam.the_scam': 'La Estafa',
    'scam.prevention': 'Prevención',
    'scam.promise_title': 'La Promesa Dunecamps',
    'scam.ready': '¿Listo para reservar con tranquilidad?',
    'scam.explore_action': 'Explorar campamentos de élite',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
